### ISSUE TITLE
gdrive repos

### ISSUE THREAD

**Issue by ryanjerskine** [ddurdle/repository.ddurdle#1]
Any particular reason you pulled down all of your google drive related repos (Kodi and otherwise)? Not a big deal, but I occasionally used them as reference points for using Google Drive for video playback.

**Comment by ddurdle** [comment]
You should use the kodi provided plugin.  I've decided to make my work private.

**Comment by asw13537** [comment]
I think his plugin / videostream using  drive API V2. Now using V3. Kodi official add-on works fine. Just a shame you didnt update with the drive changes.

**Comment by ryanjerskine** [comment]
Totally understandable thanks for the update!
